FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git
RUN $AG update && $AG install curl

COPY subset/security .
COPY subset/helpers/reporting_utils .
RUN cd login_test  && ./gradlew shadowJar
CMD ["./test_login"]
