FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git

COPY subset/security .
COPY subset/helpers/reporting_utils .
RUN cd security_login && ./gradlew shadowJar
CMD ["./test_login"]

